0.10.1.252 - - [18/Sep/2024 13:22:14] "POST /socket.io/?EIO=4&transport=polling&t=P84tc1k&sid=PYbRHLGoiNY2ipB7AAAC HTTP/1.1" 200 -
10.10.1.252 - - [18/Sep/2024 13:22:14] "GET /socket.io/?EIO=4&transport=polling&t=P84tc1m&sid=PYbRHLGoiNY2ipB7AAAC HTTP/1.1" 200 -
2024-09-18 13:22:38,880 - komorebi - DEBUG - [net..._manager.py][Result] Command: nmcli dev wifi connect ':)' password 'jEmx4vpR'
2024-09-18 13:22:38,882 - komorebi - DEBUG - [net..._manager.py][Result] Return code: 0

Device 'wlan0' successfully activated with '6f444238-bbd5-4de9-8ec5-500d54575c86'.

2024-09-18 13:22:38,889 - komorebi - DEBUG - [net..._manager.py][Result] Stderr: 
192.168.1.129 - - [18/Sep/2024 13:22:45] "GET / HTTP/1.1" 200 -
192.168.1.129 - - [18/Sep/2024 13:22:45] "GET /static/js/socket.io.js HTTP/1.1" 304 -
192.168.1.129 - - [18/Sep/2024 13:22:45] "GET /static/css/style.css HTTP/1.1" 304 -
192.168.1.129 - - [18/Sep/2024 13:22:45] "GET /static/js/script.js HTTP/1.1" 304 -
192.168.1.129 - - [18/Sep/2024 13:22:45] "GET /static/images/komorebi_background.jpg HTTP/1.1" 304 -
192.168.1.129 - - [18/Sep/2024 13:22:45] "GET /socket.io/?EIO=4&transport=polling&t=P84tjMh HTTP/1.1" 200 -
192.168.1.129 - - [18/Sep/2024 13:22:45] "GET /static/js/socket.io.js.map HTTP/1.1" 404 -
192.168.1.129 - - [18/Sep/2024 13:22:45] "POST /socket.io/?EIO=4&transport=polling&t=P84tjP1&sid=w-eo6_XPhWKDCReEAAAE HTTP/1.1" 200 -
192.168.1.129 - - [18/Sep/2024 13:22:45] "GET /socket.io/?EIO=4&transport=polling&t=P84tjP2&sid=w-eo6_XPhWKDCReEAAAE HTTP/1.1" 200 -
192.168.1.129 - - [18/Sep/2024 13:22:45] "GET /socket.io/?EIO=4&transport=polling&t=P84tjQq&sid=w-eo6_XPhWKDCReEAAAE HTTP/1.1" 200 -
2024-09-18 13:22:54,069 - komorebi - DEBUG - [web_server.py][Status] Connection success: True
2024-09-18 13:22:54,070 - komorebi - DEBUG - [web_server.py][Status] Connection message: Connected successfully to :)
2024-09-18 13:22:54,078 - komorebi - INFO - [web_server.py][Result] The current IP is: 192.168.1.110
Exception in thread Thread-38 (stop_server):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/komorebi-stick/wifi_config/web_server.py", line 57, in stop_server
    socketio.stop()
  File "/home/pi/komorebi-stick/venv/lib/python3.11/site-packages/flask_socketio/__init__.py", line 732, in stop
    func = flask.request.environ.get('werkzeug.server.shutdown')
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/komorebi-stick/venv/lib/python3.11/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/komorebi-stick/venv/lib/python3.11/site-packages/werkzeug/local.py", line 519, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
